### PR TITLE
Fix settings subroutes get

### LINKED ISSUE #225: Reset settings with sub-settings routes
With sub-settings routes (ex: `/indexes/:uid/settings/displayed-attribute`):
- reset settings with sub-settings routes, the new default value should be put to its default value ([see the docs for the different default values](https://docs.meilisearch.com/reference/features/settings.html#settings))
- get the settings with the general settings routes -> the new value is taken into account -> ok
- get the settings with the subsettings route -> get `null` for searchable attributes and displayed attribute instead of `["*"]`

⚠️ Add tests

### PR DESCRIPTION
**Pull request by MarinPostma**
Fix #225

### CODE REVIEW

File: meilisearch-http/tests/stats/mod.rs [hunk 1]
```diff
@@ -54,11 +54,8 @@ async fn stats() {
     assert_eq!(code, 202, "{}", response);
     assert_eq!(response["updateId"], 0);
 
-    let (response, code) = server.stats().await;
-
-    assert_eq!(code, 200, "{}", response);
-
-    index.wait_update_id(0).await;
+    let response = index.wait_update_id(0).await;
+    println!("response: {}", response);
```
Comment (MarinPostma) [inline meilisearch-http/tests/stats/mod.rs:58]: this is here on purpose, I tend to have this test break because of too many files open, and this is reported here.

**Review by curquiza — APPROVED** [review]
👌

**Comment by MarinPostma** [comment]
bors merge
